#!/bin/bash

phenonn train-big \
    --features_dir /net/nfs/ssd1/sbarbu/PhenoNN/data/feature \
    --target_dir /net/nfs/ssd1/sbarbu/PhenoNN/data/data_taget \
    --row_min 900 \
    --row_max 1099 \
    --col_min 1500 \
    --col_max 1699 \
    --train_years 1993-2010 \
    --val_years 2011-2019 \
    --n_sites_per_epoch 100 \
    --n_years_per_epoch 5 \
    --n_val_sites 100 \
    --type lstm \
    --hidden_size 512 \
    --dropout 0.1 \
    --num_epochs 1 \
    --num_layers 2 \
    --learning_rate 1e-4 \
    --output_dir ./runs/ \
    --experiment test
